version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: NARENDRA-642/first-py-cicd/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: NARENDRA-642/first-py-cicd/start_container.sh
      timeout: 300
      runas: root